/** Mschulz
 *This is a program Designed to print the words "Knowledge is power" in
 *three different ways
 * Comp 170 Section 020
 * @author Marc Schulz
 * @version 1/14/02
 */
public class KnowledgeIsPower
{
     //These are Three different printouts of Knowledge is power
     
     public static void main (String[] args)
     
     {
         //Used to make the Phrase Knowledge is Power on One line.
         System.out.println ("Knowledge is Power");
         //Used to make each word appear on a separate line 
         System.out.println ("Knowledge");
         System.out.println ("    is");
         System.out.println ("  Power");
         //Used to make a box around Knowledge is power
         System.out.println ("========================");
         System.out.println ("|  Knowledge is Power  |");
         System.out.println ("========================");
       }
         }
         
