//*******************************************************//
//This Counts from 1 to 5 in English, French, and Spanish//
//                                                       //
//Author: Marc Schulz                                    //
//Version: January 21, 2003                              //
//*******************************************************//



public class Count
{

    public static void main (String[] args)
    {
    //// English 
	System.out.println ("one two three four five");
	//French
	System.out.println ("un deux trois quatre cinq");
	//Spanish
	System.out.println ("uno dos tres cuatro cinco");

    }
}

