
//********************************//
/* Prints The poem Roses are Red!//
/*                               //
/* @author Marc Schulz           //
/* @version January 21, 2003     //
//********************************/

public class RosesAreRed
{ public static void main (String[] args )
 
  {  System.out.println("Roses are Red");
     System.out.println("Violets are Blue");
     System.out.println("Sugar is sweet");
     System.out.println("And so are you!");
     
   }
}